-- Scheduler App - Initial HANA Cloud persistence schema
-- Idempotent version for direct SQL execution in SAP HANA Cloud.
--
-- Behavior:
--   - Creates schema SCHEDULER_APP if missing
--   - Creates all required tables, indexes, and constraints if missing
--   - Seeds latest publication rows if missing

DO
BEGIN
  DECLARE schema_count INTEGER;

  SELECT COUNT(*) INTO schema_count
  FROM SYS.SCHEMAS
  WHERE SCHEMA_NAME = 'SCHEDULER_APP';

  IF :schema_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SCHEMA SCHEDULER_APP';
  END IF;
END;

SET SCHEMA SCHEDULER_APP;

DO
BEGIN
  DECLARE table_count INTEGER;

  SELECT COUNT(*) INTO table_count
  FROM SYS.TABLES
  WHERE SCHEMA_NAME = 'SCHEDULER_APP'
    AND TABLE_NAME = 'SCHEDULER_PROJECTS';

  IF :table_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE COLUMN TABLE SCHEDULER_PROJECTS (
        ID NVARCHAR(64) NOT NULL,
        NAME NVARCHAR(255) NOT NULL,
        CREATED_AT TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP NOT NULL,
        ACTIVE_VERSION_ID NVARCHAR(64),
        REVISION INTEGER NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(255),
        UPDATED_BY NVARCHAR(255),
        PRIMARY KEY (ID)
      )
    ';
  END IF;
END;

DO
BEGIN
  DECLARE table_count INTEGER;

  SELECT COUNT(*) INTO table_count
  FROM SYS.TABLES
  WHERE SCHEMA_NAME = 'SCHEDULER_APP'
    AND TABLE_NAME = 'SCHEDULER_VERSIONS';

  IF :table_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE COLUMN TABLE SCHEDULER_VERSIONS (
        ID NVARCHAR(64) NOT NULL,
        PROJECT_ID NVARCHAR(64) NOT NULL,
        VERSION_NUMBER INTEGER NOT NULL,
        LABEL NVARCHAR(255),
        PARENT_VERSION_ID NVARCHAR(64),
        CREATED_AT TIMESTAMP NOT NULL,
        SNAPSHOT_JSON NCLOB NOT NULL,
        SNAPSHOT_SCHEMA_VERSION INTEGER NOT NULL DEFAULT 3,
        SNAPSHOT_HASH NVARCHAR(128),
        CREATED_BY NVARCHAR(255),
        PRIMARY KEY (ID),
        CONSTRAINT FK_SCHEDULER_VERSIONS_PROJECT
          FOREIGN KEY (PROJECT_ID) REFERENCES SCHEDULER_PROJECTS (ID)
          ON DELETE CASCADE
      )
    ';
  END IF;
END;

DO
BEGIN
  DECLARE index_count INTEGER;

  SELECT COUNT(*) INTO index_count
  FROM SYS.INDEXES
  WHERE SCHEMA_NAME = 'SCHEDULER_APP'
    AND INDEX_NAME = 'UX_SCHEDULER_VERSIONS_PROJECT_NUMBER';

  IF :index_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE UNIQUE INDEX UX_SCHEDULER_VERSIONS_PROJECT_NUMBER
      ON SCHEDULER_VERSIONS (PROJECT_ID, VERSION_NUMBER)
    ';
  END IF;
END;

DO
BEGIN
  DECLARE index_count INTEGER;

  SELECT COUNT(*) INTO index_count
  FROM SYS.INDEXES
  WHERE SCHEMA_NAME = 'SCHEDULER_APP'
    AND INDEX_NAME = 'IX_SCHEDULER_VERSIONS_PROJECT_CREATED';

  IF :index_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE INDEX IX_SCHEDULER_VERSIONS_PROJECT_CREATED
      ON SCHEDULER_VERSIONS (PROJECT_ID, CREATED_AT DESC)
    ';
  END IF;
END;

DO
BEGIN
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN END;

  EXECUTE IMMEDIATE '
    ALTER TABLE SCHEDULER_PROJECTS
    ADD CONSTRAINT FK_SCHEDULER_PROJECTS_ACTIVE_VERSION
    FOREIGN KEY (ACTIVE_VERSION_ID) REFERENCES SCHEDULER_VERSIONS (ID)
  ';
END;

DO
BEGIN
  DECLARE table_count INTEGER;

  SELECT COUNT(*) INTO table_count
  FROM SYS.TABLES
  WHERE SCHEMA_NAME = 'SCHEDULER_APP'
    AND TABLE_NAME = 'SCHEDULER_PUBLICATIONS';

  IF :table_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE COLUMN TABLE SCHEDULER_PUBLICATIONS (
        PUBLICATION_KEY NVARCHAR(100) NOT NULL,
        PAYLOAD_TYPE NVARCHAR(30) NOT NULL,
        PAYLOAD_JSON NCLOB NOT NULL,
        PUBLISHED_AT TIMESTAMP NOT NULL,
        PUBLISHED_BY NVARCHAR(255),
        SOURCE_PROJECT_ID NVARCHAR(64),
        SOURCE_VERSION_ID NVARCHAR(64),
        PAYLOAD_HASH NVARCHAR(128),
        PRIMARY KEY (PUBLICATION_KEY),
        CONSTRAINT FK_SCHEDULER_PUBLICATIONS_PROJECT
          FOREIGN KEY (SOURCE_PROJECT_ID) REFERENCES SCHEDULER_PROJECTS (ID)
          ON DELETE SET NULL,
        CONSTRAINT FK_SCHEDULER_PUBLICATIONS_VERSION
          FOREIGN KEY (SOURCE_VERSION_ID) REFERENCES SCHEDULER_VERSIONS (ID)
          ON DELETE SET NULL,
        CONSTRAINT CK_SCHEDULER_PUBLICATIONS_TYPE
          CHECK (PAYLOAD_TYPE IN (''summary'', ''vats''))
      )
    ';
  END IF;
END;

DO
BEGIN
  DECLARE table_count INTEGER;

  SELECT COUNT(*) INTO table_count
  FROM SYS.TABLES
  WHERE SCHEMA_NAME = 'SCHEDULER_APP'
    AND TABLE_NAME = 'SCHEDULER_APP_STATE';

  IF :table_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE COLUMN TABLE SCHEDULER_APP_STATE (
        STATE_KEY NVARCHAR(100) NOT NULL,
        STATE_JSON NCLOB NOT NULL,
        UPDATED_AT TIMESTAMP NOT NULL,
        UPDATED_BY NVARCHAR(255),
        PRIMARY KEY (STATE_KEY)
      )
    ';
  END IF;
END;

MERGE INTO SCHEDULER_PUBLICATIONS AS target
USING (
  SELECT
    'summary.latest' AS PUBLICATION_KEY,
    'summary' AS PAYLOAD_TYPE,
    '{}' AS PAYLOAD_JSON,
    CURRENT_UTCTIMESTAMP AS PUBLISHED_AT
  FROM DUMMY
) AS source
ON target.PUBLICATION_KEY = source.PUBLICATION_KEY
WHEN NOT MATCHED THEN
  INSERT (PUBLICATION_KEY, PAYLOAD_TYPE, PAYLOAD_JSON, PUBLISHED_AT)
  VALUES (source.PUBLICATION_KEY, source.PAYLOAD_TYPE, source.PAYLOAD_JSON, source.PUBLISHED_AT);

MERGE INTO SCHEDULER_PUBLICATIONS AS target
USING (
  SELECT
    'vats.latest' AS PUBLICATION_KEY,
    'vats' AS PAYLOAD_TYPE,
    '{}' AS PAYLOAD_JSON,
    CURRENT_UTCTIMESTAMP AS PUBLISHED_AT
  FROM DUMMY
) AS source
ON target.PUBLICATION_KEY = source.PUBLICATION_KEY
WHEN NOT MATCHED THEN
  INSERT (PUBLICATION_KEY, PAYLOAD_TYPE, PAYLOAD_JSON, PUBLISHED_AT)
  VALUES (source.PUBLICATION_KEY, source.PAYLOAD_TYPE, source.PAYLOAD_JSON, source.PUBLISHED_AT);
